- name: SSH configurations
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?{{ item.key }}'
    line: "{{ item.key }} {{ item.value }}"
    state: present
  with_items:
    - { key: "X11Forwarding", value: "no" }
    - { key: "MaxAuthTries", value: "3" }
    - { key: "IgnoreRhosts", value: "yes" }
    - { key: "HostbasedAuthentication", value: "no" }
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PermitEmptyPasswords", value: "no" }
    - { key: "PasswordAuthentication", value: "no" }
    - { key: "Ciphers", value: "aes128-ctr,aes192-ctr,aes256-ctr" }
    - { key: "MACs", value: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256" }
    - { key: "KexAlgorithms", value: "curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256" } 
    - { key: "LoginGraceTime", value: "60" }
  notify: restart ssh

