# common include add new user and config ssh service.
- name: Setup common 
  hosts: common
  become: yes
  roles:
    - role: common

- name: Setup webserver 
  hosts: webserver
  become: yes
  roles:
    - role: webserver
